apiVersion: v1
kind: Pod
metadata:
  name: frontend-build
spec:
  containers:
    - name: gcloud
      image: 'google/cloud-sdk:slim'  # Using the slim version of the gcloud image
      command: [ "sleep" ]
      args: [ "infinity" ]
 
    - name: docker
      image: 'docker:19.03.12'
      privileged: true
      command: [ "sleep" ]
      args: [ "infinity" ]
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
 
    - name: node
      image: 'node:20-slim'  # Using a slim image for Node.js version 20
      command: [ "sleep" ]
      args: [ "infinity" ]
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket