apiVersion: v1
kind: Pod
metadata:
  name: jenkins-k8s-agent
spec:
  containers:
    - name: gcloud
      image: 'google/cloud-sdk:latest'

    - name: docker
      image: 'docker:19.03.12'
      privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock

    - name: node
      image: 'node:16'
      command:
        - cat
      tty: true

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
