apiVersion: v1
kind: Pod
metadata:
  name: jenkins-k8s-agent
spec:
  containers:
    - name: gcloud
      image: 'google/cloud-sdk:slim'

    - name: docker
      image: 'docker:19.03.12'
      privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
