pipeline {
    agent any
    environment {
        REGISTRY = "us-central1-docker.pkg.dev/burner-ganprasa2/lloyds-repo"
        IMAGE_NAME = "hello-world-nextjs"
        IMAGE_TAG = "v1"
        SONARQUBE = "sonarqube"
    }
    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    sh "docker run --rm -e SONAR_HOST_URL=${SONARQUBE} -v $(pwd):/usr/src sonarsource/sonar-scanner-cli"
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    sh "docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }
        stage('Deploy to GKE') {
            steps {
                script {
                    sh 'kubectl apply -f kubernetes/deployment.yaml'
                    sh 'kubectl apply -f kubernetes/service.yaml'
                }
            }
        }
    }
}
